routes/web.php
<?php
/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

//Route::get('/', function () {
//    return view('welcome');
//});

Route::prefix('admin')->group(function() {
    Route::get('/',
        function() {
        return redirect('admin/dashboard');
    });
    AdvancedRoute::controller('dashboard', 'Admin\Dashboard');
    AdvancedRoute::controller('auth', 'Admin\AdminAuthController');
    AdvancedRoute::controller('dashboard', 'Admin\Dashboard');
    AdvancedRoute::controller('configs', 'Admin\Configs');
    AdvancedRoute::controller('roles', 'Admin\Roles');
    AdvancedRoute::controller('admins', 'Admin\Admins');
    AdvancedRoute::controller('users', 'Admin\Users');
    AdvancedRoute::controller('paragraphs', 'Admin\Paragraphs');
    AdvancedRoute::controller('partners', 'Admin\Partners');
    AdvancedRoute::controller('contacts', 'Admin\Contacts');
    AdvancedRoute::controller('subscribers', 'Admin\Subscribers');
    AdvancedRoute::controller('options', 'Admin\Options');
    AdvancedRoute::controller('pages', 'Admin\Pages');
    AdvancedRoute::controller('slides', 'Admin\Slides');
    AdvancedRoute::controller('charters', 'Admin\Charters');
    AdvancedRoute::controller('groups', 'Admin\Groups');
});
AdvancedRoute::controller('auth', 'AuthController');
Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
AdvancedRoute::controller('contacts', 'Contacts');
AdvancedRoute::controller('pages', 'Pages');
AdvancedRoute::controller('subscribers', 'Subscribers');
AdvancedRoute::controller('register', 'Register');
AdvancedRoute::controller('charters', 'Charters');
AdvancedRoute::controller('groups', 'Groups');

Route::any('/terms-and-conditions', 'Pages@termsAndConditions');
Route::any('/contact-us', 'Pages@contactUs');
Route::any('/about-us', 'Pages@aboutUs');
Route::any('/', 'Pages@home');

app/Models/BaseModel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use Request;
use DB;
use \Eventviva\ImageResize;
use Config;
use File;
use App\Libs\Misc;

class BaseModel extends Model {

    public function makeSlug($text, $field, $object) {
        if (@$object->id)
            $this->where("id", "!=", $object->id);
        $count = $this->where($field, "=", $text)->count();
        if ($count > 1) {
            $slug = Misc::slug($text) . '-' . $count;
        } else {
            $slug = Misc::slug($text);
        }
        $object->slug = str_limit($slug, 50);
        $object->save();
    }

    public function uploadAndResize($field, $object, $imageSizes = []) {
        if (!$imageSizes) {
            $imageSizes = Config::get('settings.imageSizes');
        }
        $uploadPath = 'uploads/';
        if (Request::hasFile($field) && Request::file($field)->isValid()) {
            $image = Request::file($field);
            $fileName = str_random(10) . time() . '.' . $image->getClientOriginalExtension();
            Request::file($field)->move($uploadPath, $fileName);
            $filePath = $uploadPath . $fileName;
            if ($imageSizes) {
                foreach ($imageSizes as $key => $value) {
                    $value = explode(',', $value);
                    $type = $value[0];
                    $dimensions = explode('x', $value[1]);
                    if (!File::exists($uploadPath . $key)) {
                        mkdir($uploadPath . $key);
                    }
                    $thumbPath = $uploadPath . $key . '/' . $fileName;
                    $image = new ImageResize($filePath);
                    $image->quality_jpg = 90;
                    $image->quality_png = 9;
                    if ($type == 'resize')
                        $type = 'resizeToBestFit';
                    $image->$type($dimensions[0], $dimensions[1]);
                    $image->save($thumbPath);
                }
                //@unlink($filePath);
            }
            if ($object->$field) {
                Misc::deleteImage($object->$field);
            }
            $object->$field = $fileName;
            $object->save();
        }
    }

    public function uploadAndResizeMultiple($file, $object, $field, $imageSizes = []) {
        if (!$imageSizes) {
            $imageSizes = Config::get('settings.imageSizes');
        }
        $uploadPath = 'uploads/';
        if ($file) {
            $fileName = str_random(10) . time() . '.' . $file->getClientOriginalExtension();
            $file->move($uploadPath, $fileName);
            $filePath = $uploadPath . $fileName;
            if ($imageSizes) {
                foreach ($imageSizes as $key => $value) {
                    $value = explode(',', $value);
                    $type = $value[0];
                    $dimensions = explode('x', $value[1]);
                    if (!File::exists($uploadPath . $key)) {
                        mkdir($uploadPath . $key);
                    }
                    $thumbPath = $uploadPath . $key . '/' . $fileName;
                    $image = new ImageResize($filePath);
                    $image->quality_jpg = 90;
                    if ($type == 'resize')
                        $type = 'resizeToBestFit';
                    $image->$type($dimensions[0], $dimensions[1]);
                    $image->save($thumbPath);
                }
                @unlink($filePath);
            }
            if ($object->$field) {
                Misc::deleteImage($object->$field);
            }
            $object->$field = $fileName;
            $object->save();
        }
    }

    public function uploadFile($field, $object) {
        $uploadPath = 'uploads/';
        if (Request::hasFile($field) && Request::file($field)->isValid()) {
            $file = Request::file($field);
            $fileName = str_random(10) . time() . '.' . $file->getClientOriginalExtension();
            Request::file($field)->move($uploadPath, $fileName);
            $filePath = $uploadPath . $fileName;
            if ($object->$field) {
                Misc::deleteFile($object->$field);
            }
            $object->$field = $fileName;
            $object->save();
        }
    }

    public function scopePublished($query) {
        $query->where('published', '=', 1);
    }

    public function scopeUnpublished($query) {
        $query->where('published', '=', 0);
    }

//    public function getCreatedAtAttribute($date) {
//        return Carbon::parse($date)->format('d-m-Y H:i:s a');
//    }
    public function getCreatedAtAttribute($date) {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('Y-m-d g:i a');
    }

    public function getUpdatedAtAttribute($date) {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('Y-m-d g:i a');
    }

}

resources/views/admin/admins/change-password.blade.php
@extends('admin.layouts.master')

@section('title')
<h3><i class="fa fa-angle-right"></i>{{ trans('admin.Change password') }}</h3>
@stop

@section('content')
{!! Form::model($row, ['url' => 'admin/'.$module.'/change-password', 'method' => 'post','class'=>'form-horizontal style-form','enctype'=>'multipart/form-data'] ) !!}
@php $input='old_password'; @endphp
<div class="form-group {{ $errors->has($input) ? 'has-error' : '' }}">
    {!! Form::label($input,trans('admin.Old password'),['class' => 'col-md-2 control-label']) !!}
    <div class="col-md-6">
        {!! Form::password($input,['class'=>'form-control','required'=>'required']) !!}
        @foreach($errors->get($input) as $message)
        <span class = 'help-inline text-danger'>{{ $message }}</span>
        @endforeach
    </div>
</div>
@php $input='password'; @endphp
<div class="form-group {{ $errors->has($input) ? 'has-error' : '' }}">
    {!! Form::rawLabel($input,trans('admin.Password'),['class' => 'col-md-2 control-label']) !!}
    <div class="col-md-6">
        {!! Form::password($input,['class'=>'form-control']) !!}
        @foreach($errors->get($input) as $message)
        <span class = 'help-inline text-danger'>{{ $message }}</span>
        @endforeach
    </div>
</div>
@php $input='password_confirmation'; @endphp
<div class="form-group {{ $errors->has($input) ? 'has-error' : '' }}">
    {!! Form::rawLabel($input,trans('admin.Password confirmation'),['class' => 'col-md-2 control-label']) !!}
    <div class="col-md-6">
        {!! Form::password($input,['class'=>'form-control']) !!}
        @foreach($errors->get($input) as $message)
        <span class = 'help-inline text-danger'>{{ $message }}</span>
        @endforeach
    </div>
</div>
{!! Form::submit(trans('admin.Save') ,['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}
@stop

resources/views/admin/admins/create.blade.php
@extends('admin.layouts.master')

@section('title')
<h3><i class="fa fa-angle-right"></i>{{ trans('admin.Create') }} {{trans("admin.Administrator")}}</h3>
<a href="admin/{{$module}}" class="btn btn-theme04"><i class="fa fa-backward"></i> {{trans('admin.Go back')}}</a>
@stop

@section('content')
{!! Form::model($row, ['url' => 'admin/'.$module.'/create', 'method' => 'post','class'=>'form-horizontal style-form','enctype'=>'multipart/form-data'] ) !!}
@include('admin.'.$module.'.form',$row)
{!! Form::submit(trans('admin.Save') ,['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}
@stop

resources/views/admin/admins/edit-account.blade.php
@extends('admin.layouts.master')

@section('title')
<h3><i class="fa fa-angle-right"></i>{{ trans('admin.Edit account') }}</h3>
@stop

@section('content')
{!! Form::model($row, ['url' => 'admin/'.$module.'/edit-account', 'method' => 'post','class'=>'form-horizontal style-form','enctype'=>'multipart/form-data'] ) !!}
@php $input='name'; @endphp
<div class="form-group {{ $errors->has($input) ? 'has-error' : '' }}">
    {!! Form::rawLabel($input,trans('admin.Name'),['class' => 'col-md-2 control-label']) !!}
    <div class="col-md-6">
        {!! Form::text($input,null,['class'=>'form-control']) !!}
        @foreach($errors->get($input) as $message)
        <span class = 'help-inline text-danger'>{{ $message }}</span>
        @endforeach
    </div>
</div>
@php $input='email'; @endphp
<div class="form-group {{ $errors->has($input) ? 'has-error' : '' }}">
    {!! Form::rawLabel($input,trans('admin.Email'),['class' => 'col-md-2 control-label']) !!}
    <div class="col-md-6">
        {!! Form::email($input,null,['class'=>'form-control']) !!}
        @foreach($errors->get($input) as $message)
        <span class = 'help-inline text-danger'>{{ $message }}</span>
        @endforeach
    </div>
</div>
{!! Form::submit(trans('admin.Save') ,['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}
@stop

resources/views/admin/admins/edit.blade.php
@extends('admin.layouts.master')

@section('title')
<h3><i class="fa fa-angle-right"></i>{{ trans('admin.Edit') }} {{trans("admin.Administrator")}}</h3>
<a href="admin/{{$module}}" class="btn btn-theme04"><i class="fa fa-backward"></i> {{trans('admin.Go back')}}</a>
@stop

@section('content')
{!! Form::model($row, ['url' => 'admin/'.$module.'/edit/'.$row->id, 'method' => 'post','class'=>'form-horizontal style-form','enctype'=>'multipart/form-data'] ) !!}
@include('admin.'.$module.'.form',$row)
{!! Form::submit(trans('admin.Save') ,['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}
@stop

resources/views/admin/admins/form.blade.php
{!! Form::hidden("admin_id",App\Libs\Adminauth::user()->id,['class'=>'form-control']) !!}
@php $input='name'; @endphp
<div class="form-group {{ $errors->has($input) ? 'has-error' : '' }}">
    {!! Form::rawLabel($input,trans('admin.Name')."<em class='red'>*</em>",['class' => 'col-md-2 control-label']) !!}
    <div class="col-md-6">
        {!! Form::text($input,null,['class'=>'form-control']) !!}
        @foreach($errors->get($input) as $message)
        <span class = 'help-inline text-danger'>{{ $message }}</span>
        @endforeach
    </div>
</div>
@php $input='email'; @endphp
<div class="form-group {{ $errors->has($input) ? 'has-error' : '' }}">
    {!! Form::rawLabel($input,trans('admin.Email')."<em class='red'>*</em>",['class' => 'col-md-2 control-label']) !!}
    <div class="col-md-6">
        {!! Form::email($input,null,['class'=>'form-control']) !!}
        @foreach($errors->get($input) as $message)
        <span class = 'help-inline text-danger'>{{ $message }}</span>
        @endforeach
    </div>
</div>
@php $input='password'; @endphp
<div class="form-group {{ $errors->has($input) ? 'has-error' : '' }}">
    {!! Form::rawLabel($input,trans('admin.Password')."<em class='red'>*</em>",['class' => 'col-md-2 control-label']) !!}
    <div class="col-md-6">
        {!! Form::password($input,['class'=>'form-control']) !!}
        @foreach($errors->get($input) as $message)
        <span class = 'help-inline text-danger'>{{ $message }}</span>
        @endforeach
    </div>
</div>
@php $input='password_confirmation'; @endphp
<div class="form-group {{ $errors->has($input) ? 'has-error' : '' }}">
    {!! Form::rawLabel($input,trans('admin.Password confirmation')."<em class='red'>*</em>",['class' => 'col-md-2 control-label']) !!}
    <div class="col-md-6">
        {!! Form::password($input,['class'=>'form-control']) !!}
        @foreach($errors->get($input) as $message)
        <span class = 'help-inline text-danger'>{{ $message }}</span>
        @endforeach
    </div>
</div>

@php $input='published'; @endphp
<div class="form-group">
    {!! Form::rawLabel($input,trans('admin.Published'),['class' => 'col-md-2 control-label']) !!}
    <div class="col-md-10">
        <label class="checkbox-inline">
            {!! Form::radio($input,1,null,[]) !!} {{trans("admin.Yes")}}
        </label>
        <label class="checkbox-inline">
            {!! Form::radio($input,0,null,[]) !!} {{trans("admin.No")}}
        </label>
    </div>
</div>
<?php
if (@$roles) {
    $final_roles = array();
    $category = "";
    foreach ($roles as $role) {
        if ($category != $role->category) {
            $category = $role->category;
            unset($value);
        }
        $key = $role->category;
        $value[$role->id] = $role->title;
        $final_roles[$key] = $value;
    }
}
?>
<div class="clearfix"></div>
@if($final_roles)
<div class="control-group">
    <label class="control-label" for="permissions">
        <h3>{{trans('admin.Permissions')}}
            <label >
                <input id="selectAll" for="Paragraphs" name="selectAll" type="checkbox" value="1">
                {{trans('admin.Select All')}}
            </label>
        </h3>
    </label>
</div>
@if($final_roles)
<div class="control-group">
    <div class="table-responsive">
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered display resize ">
            <thead>
                <tr>
                    <th width="20%">{{trans('admin.Module')}}</th>
                    <th width="80%">{{trans('admin.Actions')}}</th>
                </tr>
            </thead>
            @foreach ($final_roles as $key => $value)
            <tr>
                <td>
                    <label class="col-md-12 control-label role_head">
                        {!! Form::checkbox('heades[]',1,null,['class'=>'heads main_head_'.str_replace(' ','',$key),'id'=>$key,'for'=>str_replace(' ','',$key)]) !!} &nbsp;&nbsp;&nbsp;&nbsp;{{ucfirst($key)}}
                    </label>
                </td>
                <td>
                    @foreach ($value as $k => $v)
                    <div class="col-md-3">

                        <label class="col-md-12 control-label" for="role_{{$k}}">{!! Form::checkbox('role_list[]',$k,null,['class'=>'childs head_'.str_replace(' ','',$key),'id'=>'role_'.$k,'for'=>str_replace(' ','',$key)]) !!} {{ucfirst($v)}}</label>
                    </div>
                    @endforeach
                </td>
            </tr>
            @endforeach;
        </table>
    </div>
</div>
@endif
@endif
<div class="clearfix"></div>
@section('javascripts')
<script>
    $(function () {
        $("#selectAll").change(function () {
            if ($(this).is(':checked')) {
                $('.heads, .childs').prop('checked', true);
            } else {
                $('.heads, .childs').prop('checked', false);
            }
            console.log("yes");
        });
        $(".heads").change(function () {
            var key = $(this).attr("for");
            console.log(".head_" + key);
            $(".head_" + key).prop('checked', $(this).prop("checked"));
        });
        $(".childs").change(function () {
            var head = $(this).attr("for");
            if ($(this).is(':checked')) {
                $('.main_head_' + head).prop('checked', true);
            } else {
                if ($(".head_" + head + ":checked").size() == 0) {
                    $('.main_head_' + head).prop('checked', false);
                }
            }
        });
        $(".childs").each(function (index) {
            var head = $(this).attr("for");
            if ($(this).is(':checked')) {
                $('.main_head_' + head).prop('checked', true);
            } else {
                if ($(".head_" + head + ":checked").size() == 0) {
                    $('.main_head_' + head).prop('checked', false);
                }
            }
        });
    });
</script>
@stop

resources/views/admin/admins/index.blade.php
@extends('admin/layouts/master')

@section('title')
<h3><i class="fa fa-angle-right"></i>{{ trans('admin.List') }} {{trans("admin.Administrators")}}</h3>
@stop

@section('content')
@if(ACL::can('create-'.$module))
<a href="admin/{{$module}}/create" class="btn btn-success"><i class="fa fa-plus"></i> {{trans('admin.Create')}}</a>
@endif

@if (!$rows->isEmpty())
{!! Form::open(['url' => 'admin/'.$module.'/delete', 'method' => 'post','class'=>'form-horizontal style-form','enctype'=>'multipart/form-data'] ) !!}
<div class="table-responsive">
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered display resize data_table">
        <thead>
            <tr>
                <th width="5%">{{trans('admin.ID')}} </th>
                <th width="15%">{{trans('admin.Name')}}</th>
                <th width="15%">{{trans('admin.Email')}}</th>
                <th width="15%">{{trans('admin.Created at')}}</th>
                @if(isset($rows[0]->published))
                @if(ACL::can('publish-'.$module))
                <th width="5%">{{trans('admin.Published')}}?</th>
                @endif
                @endif
                <th width="15%">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($rows as $row)
            <tr>
                <td class="center">{{$row->id}}</td>
                <td class="center">{{$row->name}}</td>
                <td class="center">{!! $row->email !!}</td>
                <td class="center">{{$row->created_at}}</td>
                @if(isset($row->published))
                @if(ACL::can('publish-'.$module))
                <td class="center">
                    @if ($row->published == 1)
                    <a href="admin/{{$module}}/publish/0/{{$row->id}}">
                        <span style="display:none;">1</span><img src="assets/admin/img/check.png">
                    </a>
                    @else
                    <a href="admin/{{$module}}/publish/1/{{$row->id}}">
                        <span style="display:none;">0</span><img src="assets/admin/img/close.png">
                    </a>
                    @endif
                </td>
                @endif
                @endif
                <td class="center">
                    @if(ACL::can('edit-'.$module))
                    <a class="btn btn-success btn-xs" href="admin/{{$module}}/edit/{{$row->id}}" title="{{trans('admin.Edit')}}">
                        <i class="fa fa-edit"></i>
                    </a>
                    @endif
                    @if(ACL::can('view-'.$module))
                    <a class="btn btn-primary btn-xs " href="admin/{{$module}}/view/{{$row->id}}" title="{{trans('admin.View')}}">
                        <i class="fa fa-eye"></i>
                    </a>
                    @endif
                    @if(ACL::can('delete-'.$module))
                    <a class="btn btn-danger btn-xs" href="admin/{{$module}}/delete/{{$row->id}}" title="{{trans('admin.Delete')}}" data-title="{{trans('admin.Confirmation message')}}" data-confirm="{{trans('admin.Are you sure you want to delete this administrator')}}?">
                        <i class="fa fa-trash-o"></i>
                    </a>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
{!! Form::close() !!}
@else
{{trans("admin.There is no results")}}
@endif

@stop

resources/views/admin/admins/view.blade.php
@extends('admin.layouts.master')

@section('title')
<h3><i class="fa fa-angle-right"></i>{{ trans('admin.View') }} {{trans("admin.Administrator")}}</h3>
<a href="admin/{{$module}}" class="btn btn-danger"><i class="fa fa-backward"></i> {{trans('admin.Go back')}}</a>
@stop

@section('content')
@if(ACL::can('edit-'.$module))
<a href="admin/{{$module}}/edit/{{$row->id}}" class="btn btn-primary">
    <i class="fa fa-edit"></i> {{trans('admin.Edit')}}
</a>
@endif
<div class="table-responsive">
    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered pull-left">
      
        <tr>
            <td width="25%" class="align-left">{{trans('admin.Name')}}</td>
            <td width="75%" class="align-left">{{$row->name}}</td>
        </tr>
        <tr>
            <td width="25%" class="align-left">{{trans('admin.Email')}}</td>
            <td width="75%" class="align-left">{{$row->email}}</td>
        </tr>
        <tr>
            <td width="25%" class="align-left">{{trans('admin.Permissons')}}</td>
            <td width="75%" class="align-left">{{implode(", ",@$row->roles->pluck('title','id')->toArray())}}</td>
        </tr>
        <tr>
            <td width="25%" class="align-left">{{trans('admin.Published')}}</td>
            <td width="75%" class="align-left">{{($row->published)?trans('admin.Yes'):trans('admin.No')}}</td>
        </tr>
        <tr>
            <td width="25%" class="align-left">{{trans('admin.Created at')}}</td>
            <td width="75%" class="align-left">{{$row->created_at}}</td>
        </tr>
        <tr>
            <td width="25%" class="align-left">{{trans('admin.Updated at')}}</td>
            <td width="75%" class="align-left">{{$row->updated_at}}</td>
        </tr>
        @if(@$row->admin->name)
        <tr>
            <td width="25%" class="align-left">{{trans('admin.Created by')}}</td>
            <td width="75%" class="align-left">{{@$row->admin->name}}</td>
        </tr>
        @endif
    </table>
</div>
@stop